import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :nix_phoenix_template, NixPhoenixTemplateWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [hsts: true],
  https: [
    port: 443,
    cipher_suite: :strong,
    otp_app: :nix_phoenix_template,
    keyfile: System.get_env("TEMPLATE_SSL_KEY_PATH"),
    certfile: System.get_env("TEMPLATE_SSL_KEY_PATH"),
    cacertfile: System.get_env("INTERMEDIATE_CERTFILE_PATH")
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: NixPhoenixTemplate.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
